language: python
dist: trusty
sudo: required

services:
  - docker

before_install:
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports universe'
  - sudo apt-get update -qq
  - sudo apt-get install -y shellcheck
  - sudo apt-get install -y -o Dpkg::Options::="--force-confold" --force-yes docker-engine

install:
  - pip install ansible-container

script:
  - docker version
  - docker-compose version
  - docker info
  - env
  - cd tests 
  - ansible-container install git+https://github.com/${TRAVIS_REPO_SLUG},${TRAVIS_COMMIT}
  - ansible-container build

notifications:
  email: false
  # webhooks: https://galaxy.ansible.com/api/v1/notifications/
