---
# tasks file for cassandra

- name: Add apt GPG keys 
  apt_key: 
    keyserver: ha.pool.sks-keyservers.net
    id: "{{ item }}"
    state: present
  with_items:
    - 514A2AD631A57A16DD0047EC749D6EEC0353B12C
    - A26E528B271F19B9E5D8E19EA278B781FE4B2BDA 

- name: Add cassandra repo
  apt_repository:
    repo: "deb http://www.apache.org/dist/cassandra/debian 37x main"
    state: present

- name: Install cassandra
  apt:
    name: cassandra=3.7
    state: present

- name: Patch for issues.apache.org/jira/browse/CASSANDRA-11661  
  command: sed -ri 's/^(JVM_PATCH_VERSION)=.*/\1=25/' /etc/cassandra/cassandra-env.sh 

- name: Create application directories
  file:
    path: "{{ item }}"
    state: directory
    owner: cassandra
    group: cassandra 
    mode: 0777
    recurse: yes
  with_items:
    - /var/lib/cassandra
    - /etc/cassandra
    - /var/log/cassandra
